import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/Header";
import HeroSection from "@/sections/HeroSection";
import OurVision from "@/sections/OurVision";
import MarketingSolution from "@/sections/MarketingSolution";
import CaseStudies from "@/sections/CaseStudies";
import Footer from "@/Footer";
import BestCustomer from "@/sections/BestCustomer";
import OurTeam from "@/sections/OurTeam";
import LatestNews from "@/sections/LatestNews";
import GetInTouch from "@/sections/GetInTouch";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
   return (
      <>
         <Head>
            <title>Apex Marketing Solutions</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Header />
         <HeroSection />
         <OurVision />
         <MarketingSolution marketingDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elitd do eiusmod tempor incididunt ut lore magna aliqua. Quis ipsum suspendisse ultrices gravida." />
         <CaseStudies />
         <BestCustomer />
         <OurTeam />
         <LatestNews />
         <GetInTouch />
         <Footer />
      </>
   );
}
