import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/Header";
import HeroSection from "@/sections/HeroSection";
import OurVision from "@/sections/OurVision";
import MarketingSolution from "@/sections/MarketingSolution";
import CaseStudies from "@/sections/CaseStudies";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Header />
         <HeroSection />
         <OurVision />
         <MarketingSolution />
         <CaseStudies />
      </>
   );
}
